<a href="https://colab.research.google.com/github/amanzlast/10Academyweek2/blob/main/trial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

impport files

In [3]:
df=pd.read_csv('/content/Week2_challenge_data_source(CSV).csv')
df.head()

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,1.311448e+19,4/4/2019 12:01,770,4/25/2019 14:35,662,1823652,2.082014e+14,3.366496e+10,3.552121e+13,9.16456699548519E+015,...,15854611.0,2501332.0,8198936.0,9656251.0,278082303.0,14344150.0,171744450.0,8814393.0,36749741.0,308879636.0
1,1.311448e+19,4/9/2019 13:04,235,4/25/2019 8:15,606,1365104,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,...,20247395.0,19111729.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,15055145.0,53800391.0,653384965.0
2,1.311448e+19,4/9/2019 17:42,1,4/25/2019 11:58,652,1361762,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,...,19725661.0,14699576.0,17587794.0,6163408.0,229584621.0,395630.0,410692588.0,4215763.0,27883638.0,279807335.0
3,1.311448e+19,4/10/2019 0:31,486,4/25/2019 7:36,171,1321509,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,...,21388122.0,15146643.0,13994646.0,1097942.0,799538153.0,10849722.0,749039933.0,12797283.0,43324218.0,846028530.0
4,1.311448e+19,4/12/2019 20:10,565,4/25/2019 10:40,954,1089009,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,...,15259380.0,18962873.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,13910322.0,38542814.0,569138589.0

In [5]:
df.shape

(19565, 55)

In [7]:
df.columns

Index(['Bearer Id', 'Start', 'Start ms', 'End', 'End ms', 'Dur. (ms)', 'IMSI',
       'MSISDN/Number', 'IMEI', 'Last Location Name', 'Avg RTT DL (ms)',
       'Avg RTT UL (ms)', 'Avg Bearer TP DL (kbps)', 'Avg Bearer TP UL (kbps)',
       'TCP DL Retrans. Vol (Bytes)', 'TCP UL Retrans. Vol (Bytes)',
       'DL TP < 50 Kbps (%)', '50 Kbps < DL TP < 250 Kbps (%)',
       '250 Kbps < DL TP < 1 Mbps (%)', 'DL TP > 1 Mbps (%)',
       'UL TP < 10 Kbps (%)', '10 Kbps < UL TP < 50 Kbps (%)',
       '50 Kbps < UL TP < 300 Kbps (%)', 'UL TP > 300 Kbps (%)',
       'HTTP DL (Bytes)', 'HTTP UL (Bytes)', 'Activity Duration DL (ms)',
       'Activity Duration UL (ms)', 'Dur. (ms).1', 'Handset Manufacturer',
       'Handset Type', 'Nb of sec with 125000B < Vol DL',
       'Nb of sec with 1250B < Vol UL < 6250B',
       'Nb of sec with 31250B < Vol DL < 125000B',
       'Nb of sec with 37500B < Vol UL',
       'Nb of sec with 6250B < Vol DL < 31250B',
       'Nb of sec with 6250B < Vol UL < 37500B',
       'Nb of sec with Vol DL < 6250B', 'Nb of sec with Vol UL < 1250B',
       'Social Media DL (Bytes)', 'Social Media UL (Bytes)',
       'Google DL (Bytes)', 'Google UL (Bytes)', 'Email DL (Bytes)',
       'Email UL (Bytes)', 'Youtube DL (Bytes)', 'Youtube UL (Bytes)',
       'Netflix DL (Bytes)', 'Netflix UL (Bytes)', 'Gaming DL (Bytes)',
       'Gaming UL (Bytes)', 'Other DL (Bytes)', 'Other UL (Bytes)',
       'Total UL (Bytes)', 'Total DL (Bytes)'],
      dtype='object')

In [8]:
df.value_counts

<bound method DataFrame.value_counts of           Bearer Id            Start  Start ms              End  End ms  \
0      1.311448e+19   4/4/2019 12:01       770  4/25/2019 14:35     662
1      1.311448e+19   4/9/2019 13:04       235   4/25/2019 8:15     606
2      1.311448e+19   4/9/2019 17:42         1  4/25/2019 11:58     652
3      1.311448e+19   4/10/2019 0:31       486   4/25/2019 7:36     171
4      1.311448e+19  4/12/2019 20:10       565  4/25/2019 10:40     954
...             ...              ...       ...              ...     ...
19560  1.304243e+19  4/24/2019 19:57       134   4/25/2019 0:20     350
19561  7.277826e+18  4/24/2019 19:57       557   4/25/2019 5:06     183
19562  1.304243e+19  4/24/2019 19:57       438  4/24/2019 23:28     716
19563  7.349883e+18  4/24/2019 19:57       154   4/25/2019 0:54     132
19564  1.304243e+19  4/24/2019 19:57       480   4/25/2019 0:40     888

       Dur. (ms)          IMSI  MSISDN/Number          IMEI  \
0        1823652  2.082014e+14   3.366496e+10  3.552121e+13
1        1365104  2.082019e+14   3.368185e+10  3.579401e+13
2        1361762  2.082003e+14   3.376063e+10  3.528151e+13
3        1321509  2.082014e+14   3.375034e+10  3.535661e+13
4        1089009  2.082014e+14   3.369980e+10  3.540701e+13
...          ...           ...            ...           ...
19560      15749  2.082014e+14   3.363322e+10  3.552691e+13
19561      32891  2.082014e+14   3.365931e+10  3.597511e+13
19562      12656  2.082017e+14   3.376203e+10  3.522741e+13
19563      17781  2.082014e+14   3.376289e+10  3.573641e+13
19564      16925  2.082010e+14   3.365026e+10  3.515801e+13

          Last Location Name  ...  Youtube DL (Bytes)  Youtube UL (Bytes)  \
0      9.16456699548519E+015  ...          15854611.0           2501332.0
1                    L77566A  ...          20247395.0          19111729.0
2                    D42335A  ...          19725661.0          14699576.0
3                    T21824A  ...          21388122.0          15146643.0
4                    D88865A  ...          15259380.0          18962873.0
...                      ...  ...                 ...                 ...
19560                D79405C  ...           1949979.0          11208384.0
19561                D94158C  ...           5318502.0          12979569.0
19562                    NaN  ...           1825072.0           4004519.0
19563                D89509A  ...          12866953.0           4571525.0
19564                D92948B  ...                 NaN                 NaN

       Netflix DL (Bytes)  Netflix UL (Bytes)  Gaming DL (Bytes)  \
0               8198936.0           9656251.0        278082303.0
1              18338413.0          17227132.0        608750074.0
2              17587794.0           6163408.0        229584621.0
3              13994646.0           1097942.0        799538153.0
4              17124581.0            415218.0        527707248.0
...                   ...                 ...                ...
19560           2962595.0           5619719.0        340477990.0
19561          20541549.0          12735106.0        500441650.0
19562           2123158.0           2207616.0        293775479.0
19563           6696258.0           9259136.0         29868655.0
19564                 NaN                 NaN                NaN

       Gaming UL (Bytes)  Other DL (Bytes)  Other UL (Bytes)  \
0             14344150.0       171744450.0         8814393.0
1              1170709.0       526904238.0        15055145.0
2               395630.0       410692588.0         4215763.0
3             10849722.0       749039933.0        12797283.0
4              3529801.0       550709500.0        13910322.0
...                  ...               ...               ...
19560          6906179.0       596158908.0         7286089.0
19561          9811985.0       745851701.0         8691953.0
19562         16518093.0       746793152.0        14514079.0
19563         16129441.0       219768843.0        11800383.0
19564                NaN               NaN               NaN

       Total UL (Bytes)  Total DL (Bytes)
0            36749741.0       308879636.0
1            53800391.0       653384965.0
2            27883638.0       279807335.0
3            43324218.0       846028530.0
4            38542814.0       569138589.0
...                 ...               ...
19560        31549664.0       351479022.0
19561        48098511.0       539788992.0
19562        38013669.0       304254446.0
19563        42705114.0        52743227.0
19564               NaN               NaN

[19565 rows x 55 columns]>